# Generated by Django 3.0.7 on 2020-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0002_auto_20200708_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tselectcourse',
            name='tenddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tselectcourse',
            name='tstartdate',
            field=models.DateField(null=True),
        ),
    ]
