# Generated by Django 3.0.7 on 2020-07-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0004_auto_20200708_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tselectcourse',
            name='tcourse',
        ),
        migrations.RemoveField(
            model_name='tselectcourse',
            name='tterm',
        ),
        migrations.DeleteModel(
            name='Tcourse',
        ),
        migrations.DeleteModel(
            name='TSelectCourse',
        ),
        migrations.DeleteModel(
            name='Tterm',
        ),
    ]
