# Generated by Django 3.0.7 on 2020-07-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0006_tcourse_tselectcourse_tterm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tselectcourse',
            old_name='tenddate',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='tselectcourse',
            old_name='tstartdate',
            new_name='startdate',
        ),
    ]
