# Generated by Django 3.0.7 on 2020-07-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0007_auto_20200709_0542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tcourse',
            table='course',
        ),
        migrations.AlterModelTable(
            name='tselectcourse',
            table='SelectCourse',
        ),
        migrations.AlterModelTable(
            name='tterm',
            table='term',
        ),
    ]
