# Generated by Django 3.0.7 on 2020-07-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0008_auto_20200713_1702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tselectcourse',
            table='selectcourse',
        ),
    ]
