# Generated by Django 3.0.7 on 2020-07-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0003_auto_20200713_1713'),
        ('selectcourse', '0009_auto_20200713_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tcourse',
            new_name='course',
        ),
        migrations.RenameModel(
            old_name='TSelectCourse',
            new_name='selectcourse',
        ),
        migrations.RenameModel(
            old_name='Tterm',
            new_name='term',
        ),
    ]
