# Generated by Django 3.0.7 on 2020-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0010_auto_20200713_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectcourse',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
