# Generated by Django 3.0.7 on 2020-06-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AdminNo', models.CharField(max_length=45)),
                ('AdminName', models.CharField(max_length=45)),
                ('Term', models.CharField(max_length=45)),
                ('Course', models.CharField(max_length=45)),
                ('Username', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('StudNo', models.CharField(max_length=45)),
                ('StudName', models.CharField(max_length=45)),
                ('Term', models.CharField(max_length=45)),
                ('Course', models.CharField(max_length=45)),
                ('RefName', models.CharField(max_length=45)),
                ('Username', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
    ]
