# Generated by Django 3.0.7 on 2020-07-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admininfo',
            table='AdminInfo',
        ),
        migrations.AlterModelTable(
            name='studentinfo',
            table='StudentInfo',
        ),
    ]
