# Generated by Django 3.0.8 on 2020-07-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgnt', '0003_auto_20200713_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='StudID',
        ),
    ]
