# Generated by Django 3.0.7 on 2020-07-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0002_auto_20200713_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendate',
            old_name='TSelectCourse',
            new_name='selectcourse',
        ),
        migrations.RenameField(
            model_name='studentrec',
            old_name='TSelectCourse',
            new_name='selectcourse',
        ),
    ]
