# Generated by Django 3.0.8 on 2020-07-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0003_auto_20200713_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerec',
            name='matchrate',
            field=models.CharField(default=True, max_length=45),
        ),
    ]
