# Generated by Django 3.0.8 on 2020-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0005_auto_20200730_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerec',
            name='matchrate',
            field=models.CharField(default=True, max_length=45),
        ),
    ]
