# Generated by Django 3.0.8 on 2020-08-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0009_attendancerec_attendetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerec',
            name='matchrate',
        ),
    ]
