# Generated by Django 3.0.8 on 2020-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0010_remove_attendancerec_matchrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerec',
            name='attdatetime',
            field=models.DateField(null=True),
        ),
    ]
