# Generated by Django 3.0.8 on 2020-08-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0011_auto_20200801_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerec',
            name='matchrate',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
